logging:
  level:
    root: warn
    com.star: info
  file: log/blog-pro.log

mybatis:
  type-aliases-package: com.star.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true







